// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRZWMUUkKhQjvdSskaNRY5qL1-d4aqm_M',
    appId: '1:621239065023:web:8731640d42717129a2e90a',
    messagingSenderId: '621239065023',
    projectId: 'the-situationist-7c23f',
    authDomain: 'the-situationist-7c23f.firebaseapp.com',
    storageBucket: 'the-situationist-7c23f.firebasestorage.app',
    measurementId: 'G-C13H7WGM4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBes3pKO8zhSBfyrvDTi3JvaNAqwnFSk8w',
    appId: '1:621239065023:android:e9fdfe616ab0d798a2e90a',
    messagingSenderId: '621239065023',
    projectId: 'the-situationist-7c23f',
    storageBucket: 'the-situationist-7c23f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA38bEGOv46dSxgTfzQpQ9kM_OWpi2Tyls',
    appId: '1:621239065023:ios:6307fdbae02fe5f4a2e90a',
    messagingSenderId: '621239065023',
    projectId: 'the-situationist-7c23f',
    storageBucket: 'the-situationist-7c23f.firebasestorage.app',
    iosBundleId: 'app.situationist.situationist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA38bEGOv46dSxgTfzQpQ9kM_OWpi2Tyls',
    appId: '1:621239065023:ios:6307fdbae02fe5f4a2e90a',
    messagingSenderId: '621239065023',
    projectId: 'the-situationist-7c23f',
    storageBucket: 'the-situationist-7c23f.firebasestorage.app',
    iosBundleId: 'app.situationist.situationist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRZWMUUkKhQjvdSskaNRY5qL1-d4aqm_M',
    appId: '1:621239065023:web:396e3f1733e99bf3a2e90a',
    messagingSenderId: '621239065023',
    projectId: 'the-situationist-7c23f',
    authDomain: 'the-situationist-7c23f.firebaseapp.com',
    storageBucket: 'the-situationist-7c23f.firebasestorage.app',
    measurementId: 'G-2MNTCRPHM2',
  );
}
